#!/usr/bin/env bash
# a script that installs and redirects /redirect_me on nginx server

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '24i\    rewrite ^/redirect_me
